### ISSUE TITLE
Memory leaks when close to OOM

### ISSUE THREAD

**Issue by daurnimator** [philanc/luatweetnacl#3]
Lua functions such as `lua_pushlstring` can long jump out on failure.
Your code doesn't protect against this, and will end up leaking your `malloc`d buffer
e.g. https://github.com/philanc/luatweetnacl/blob/master/luatweetnacl.c#L323

Consider using `lua_newuserdata` instead of `malloc` so that you get free/automatic clean up!

**Comment by philanc** [comment]
Thanks. I will look into it.

**Comment by philanc** [comment]
If I understand correctly (I am a bit naive with the C interface, especially userdata!),
what you suggest  is to replace this sort of sequence using malloc():
	char * buf = malloc(buflen);
	some_C_func(buf, buflen, x, y, z);
	lua_pushlstring (L, buf, buflen); 
	free(buf);
	return 1;

With this:
	char * buf = lua_newuserdata(L, buflen);
	some_C_func(buf, buflen, x, y, z);
	lua_pushlstring (L, buf, buflen); 
	lua_remove(L, -2); // must remove the userdata from the stack
	// let the Lua GC get rid of the allocated userdata later
	return 1;

is it correct?

**Comment by daurnimator** [comment]
Yes, that would work. No need to call `lua_remove` either.

**Comment by daurnimator** [comment]
A different approach is to use a `luaL_Buffer` with `luaL_buffinitsize`. However that only works in 5.2+ (though you can get it via [compat-5.3](https://github.com/keplerproject/lua-compat-5.3))

**Comment by philanc** [comment]
but if I don't call `lua_remove`, the userdata I pushed is not popped and the stack keeps growing...!?  or maybe I just don't get how the stack works?

**Comment by daurnimator** [comment]
Lua will automatically clean up the stack after your c function returns.

http://www.lua.org/manual/5.3/manual.html#lua_CFunction

> To return values to Lua, a C function just pushes them onto the stack, in direct order (the first result is pushed first), and returns the number of results. Any other value in the stack below the results will be properly discarded by Lua.

**Comment by philanc** [comment]
Ah, ok! I get it. Thanks for the explanation.

**Comment by philanc** [comment]
Ok. I did replace all the malloc/free with lua_newuserdata.
Thanks for the suggestion.
