### ISSUE TITLE
Consider adding a CHANGELOG to the project

### ISSUE THREAD

**Issue by epicfilemcnulty** [philanc/luatweetnacl#5]
First of all, thanks for the project!

Would you consider adding a CHANGELOG to the project? You already have two releases, and without looking at the comments in the code, one can't really say what's been changed. And especially for this kind of library, I dare say it's really crucial to have changes between releases announced clearly.

**Comment by philanc** [comment]
Thanks for your suggestion. First of all, I am truly sorry for my ultra-late answer. I don't know how I missed your opened issue :(

luatweetnacl is now in "low maintenance" mode. Basically I don't touch it any more, except in case of a blocking bug.

If I am to change anything, I will follow your advice and add a change description item to the project README. 

Again, thanks and sorry!
