### ISSUE TITLE
Cannot install luatwwetnacl in Luarocks, seems to be connection hiccup.

### ISSUE THREAD

**Issue by asumbek** [philanc/luatweetnacl#7]
Hello, I'm trying to build Lacord into my Termux. But when I install luatweetnacl (`luarocks install luatweetnacl`), it just come up with an error. See the image below.

![Screenshot_202206163-015637](https://user-images.githubusercontent.com/71205197/173199390-d0b437b4-b20f-412d-b22e-0d8468eec821.JPEG)

**Comment by philanc** [comment]
Hi UrNightmaree,

In the screenshot, I see that Luarocks cannot connect to github.com.  The luatweetnacl is up and accessible at https://github.com/philanc/luatweetnacl.  I have no idea where the connection issue may be on your side: is it with termux? or your Luarocks installation?

I have no phone/termux environment so I cannot even try to reproduce the issue.

Have you already successfully installed Lua modules with Luarocks in termux?

**Comment by asumbek** [comment]
I have installed the old version of the module (0.3-2) and its working now. Also thanks for the your answer.
